/**
 * Licensed Materials - Property of PEG TECH INC
 *
 * (C) Copyright PEG TECH INC. 2024 ~ 2025 All Rights Reserved
 *
 * Contributors:
 *    bryan@raksmart.com - Initial implementation
 *
 *
 * Purpose: uuid utilities
 * Change log: WALLET-41 add GenerateShortID
 *
**/

package sys

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"io"
	"math/big"
	"regexp"

	sid "github.com/teris-io/shortid"
)

type alg struct {
	hashFun func([]byte) string
	decoder func(string) ([]byte, error)
}

var availableIDgenAlgs = map[string]alg{
	"sha256base64": alg{GenerateUUIDfromTxSHAHash, base64.StdEncoding.DecodeString},
}

var shortIDGenerator *sid.Shortid

func init() {
	shortIDGenerator, _ = sid.New(1, sid.DefaultABC, 2342)
}

// GenerateShortID generates a short id (length = 9)
func GenerateShortID() string {
	id, _ := shortIDGenerator.Generate()
	return id
}

// GenerateUUIDfromTxSHAHash generates SHA256 hash using Tx payload, and uses its first
// 128 bits as a UUID
func GenerateUUIDfromTxSHAHash(txData []byte) string {
	txHash := sha256.Sum256(txData)
	return uuidBytesToStr(txHash[0:16])
}

// GenerateIDWithAlg generates an ID using a custom algorithm
func GenerateIDWithAlg(customIDgenAlg string, encodedPayload string) (string, error) {
	var alg = availableIDgenAlgs[customIDgenAlg]
	if alg.hashFun != nil && alg.decoder != nil {
		var payload, err = alg.decoder(encodedPayload)
		if err != nil {
			return "", err
		}
		return alg.hashFun(payload), nil
	}
	return "", fmt.Errorf("Wrong UUID generation algorithm was given.")
}

// GenerateBytesUUID returns a UUID based on RFC 4122 returning the generated bytes
func GenerateBytesUUID() []byte {
	uuid := make([]byte, 16)
	_, err := io.ReadFull(rand.Reader, uuid)
	if err != nil {
		panic(fmt.Sprintf("Error generating UUID: %s", err))
	}

	// variant bits; see section 4.1.1
	uuid[8] = uuid[8]&^0xc0 | 0x80

	// version 4 (pseudo-random); see section 4.1.3
	uuid[6] = uuid[6]&^0xf0 | 0x40

	return uuid
}

// GenerateIntUUID returns a UUID based on RFC 4122 returning a big.Int
func GenerateIntUUID() *big.Int {
	uuid := GenerateBytesUUID()
	z := big.NewInt(0)
	return z.SetBytes(uuid)
}

// GenerateUUID returns a UUID based on RFC 4122
func GenerateUUID() string {
	uuid := GenerateBytesUUID()
	return uuidBytesToStr(uuid)
}

// ValidateUUID base on RFC 4122(uuid v4)
func ValidateUUID(uuid string) bool {
	r := regexp.MustCompile("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[8|9|aA|bB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}$")
	return r.MatchString(uuid)
}

func uuidBytesToStr(uuid []byte) string {
	return fmt.Sprintf("%x-%x-%x-%x-%x", uuid[0:4], uuid[4:6], uuid[6:8], uuid[8:10], uuid[10:])
}

// validUUID is used to check if a given string looks like a UUID
var validUUID = regexp.MustCompile(`(?i)^[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}$`)

// IsUUID returns true if the given string is a valid UUID.
func IsUUID(str string) bool {
	const uuidLen = 36
	if len(str) != uuidLen {
		return false
	}

	return validUUID.MatchString(str)
}
